
import { Product, ProductType, AvailabilityStatus, User, Role, AppSettings, Order, OrderStatus, PaymentMethod, ExpenseCategory } from './types';

// !!! ВАЖНО: ЗАМЕНИТЕ ЭТОТ ID НА ВАШ TELEGRAM ID (число) !!!
// Вы можете узнать его у бота @userinfobot
export const SUPER_ADMIN_ID = '@korea_center_kg'; 

export const I18N = {
  ru: {
    brandName: 'Jolu Textile',
    slogan: 'Мы формируем ткань — вы формируете моду',
    selectCategory: 'Выберите категорию',
    fabrics: 'Ткани',
    hardware: 'Аксессуары',
    searchPlaceholder: 'Поиск...',
    analyzing: 'Анализируем...',
    noResults: 'Ничего не найдено',
    noResultsDetail: 'Попробуйте изменить запрос',
    cart: 'Корзина',
    checkout: 'Оформить заказ',
    orderHistory: 'ИСТОРИЯ ЗАКАЗОВ',
    minOrder: 'Мин. заказ',
    factoryMinOrder: 'Мин. фабрики',
    inStock: 'В наличии',
    preorder: 'Предзаказ',
    addToCart: 'В корзину',
    edit: 'Редактировать',
    add: 'Добавить',
    openClientChat: 'Чат с менеджером',
    balance: 'БАЛАНС',
    status: 'СТАТУС',
    debt: 'Долг',
    notPaid: 'Не оплачено',
    overpayment: 'Переплата',
    payments: 'ПЛАТЕЖИ',
    uploadCheck: 'Загрузить чек',
    recordPayment: 'Записать оплату',
    amountPaid: 'ОПЛАЧЕНО',
    remaining: 'ОСТАТОК',
    cash: 'Наличные',
    transfer: 'Перевод',
    card: 'Карта',
    reorder: 'ЗАКАЗАТЬ СНОВА',
    factoryOrders: 'ЗАКАЗАНО НА ФАБРИКЕ',
    stockOrder: 'ИЗ НАЛИЧИЯ',
    sku: 'Артикул',
    gsm: 'Плотность (GSM)',
    width: 'Ширина (см)',
    youtubeLink: 'YouTube ID (11 символов)',
    confirm: 'Подтвердить',
    cancel: 'Отмена',
    save: 'Сохранить',
    close: 'Закрыть',
    reset: 'Сбросить',
    analyzingText: 'Ищем совпадения...',
    catalog: 'Каталог',
    profile: 'Профиль',
    orders: 'Заказы',
    stock: 'Склад',
    stats: 'Статистика',
    settings: 'Настройки',
    adminView: 'Админ-вид',
    clientView: 'Клиент-вид',
    switchRole: 'Переключить роль',
    title: 'Название',
    description: 'Описание',
    category: 'Категория',
    type: 'Тип',
    price: 'Цена',
    priceUsd: 'Цена USD',
    historyEmpty: 'История пуста',
    cartEmpty: 'Корзина пуста',
    stockWarning: 'Внимание: Заказ разделен',
    stockPart: 'Со склада',
    factoryPart: 'С фабрики',
    totalEst: 'Итого',
    uploadLogo: 'Загрузить лого',
    managerContact: 'Связаться с менеджером',
    revenue: 'Выручка',
    systemDebt: 'Общий долг',
    reports: 'Отчёты',
    reportsCenter: 'Центр Отчетов',
    selectReports: 'Выберите отчеты для скачивания',
    downloadSelected: 'Скачать выбранное',
    clientLedger: 'Клиентская книга',
    client: 'Клиент',
    date: 'Дата',
    amount: 'Сумма',
    totalItems: 'Всего позиций',
    avgCheck: 'Средний чек',
    expenses: 'Расходы',
    profit: 'Прибыль',
    netProfit: 'Чистая прибыль',
    purchasePrice: 'Закупка',
    logistics: 'Логистика',
    supplier: 'Поставщик',
    supplierWechat: 'WeChat',
    factoryDiscount: 'Скидка фабрики (-3%)',
    yourSavings: 'Вы экономите',
    addExpense: 'Добавить расход',
    receipt: 'Чек',
    expenseDetails: 'Детали расхода',
    availableQty: 'Доступно (Склад)',
    searchHistory: 'История поиска',
    visualSearchGallery: 'Галерея визуального поиска',
    selectAll: 'Выбрать все',
    deselectAll: 'Снять все',
    colorCard: 'Карта цветов',
    selectColor: 'Выберите цвет',
    variant: 'Вариант',
    addVariant: 'Добавить вариант',
    factoryMoqError: 'Недостаточно для заказа на фабрике',
    factoryMoqDetail: 'Остаток для дозаказа меньше минимума фабрики.',
    increaseOrder: 'Увеличьте заказ',
    favorites: 'Избранное',
    saved: 'Сохранено',
    checkCustomer: 'Проверка клиента',
    allClients: 'Все клиенты',
    selectClient: 'Выберите клиента',
    paymentHistory: 'История платежей',
    viewReceipt: 'Смотреть чек',
    userManagement: 'Управление пользователями',
    deleteUser: 'Удалить',
    role: 'Роль',
    
    // Reports Names
    rep_supplier: 'Отчет по поставщикам',
    rep_clients: 'Список клиентов',
    rep_client_ledger: 'Финансовая книга (Ledger)',
    rep_sales_all: 'Отчет по продажам (Общий)',
    rep_sales_fabric: 'Продажи (Ткани)',
    rep_sales_hardware: 'Продажи (Фурнитура)',
    rep_expenses: 'Отчет по расходам',
    rep_income: 'Отчет по доходам',
    rep_inventory: 'Инвентаризация (Остатки)',
    rep_search_logs: 'Логи поиска',

    statuses: {
      ORDERED: 'ЗАКАЗАН',
      CONFIRMED: 'ПОДТВЕРЖДЕН',
      PRODUCTION: 'В ПРОИЗВОДСТВЕ',
      TRANSIT: 'В ПУТИ',
      WAREHOUSE: 'НА СКЛАДЕ',
      READY_FOR_DELIVERY: 'ГОТОВ К ВЫДАЧЕ',
      DELIVERED: 'ДОСТАВЛЕН',
      CANCELLED: 'ОТМЕНЕН'
    },
    expenseCategories: {
      RENT: 'Аренда',
      UTILITIES: 'Коммунальные',
      SALARY: 'Зарплата',
      LOGISTICS: 'Логистика',
      MARKETING: 'Маркетинг',
      OTHER: 'Прочее'
    }
  },
  en: {
    brandName: 'Jolu Textile',
    slogan: "We shape the fabric — you shape the fashion",
    selectCategory: 'Select Category',
    fabrics: 'Fabrics',
    hardware: 'Accessories',
    searchPlaceholder: 'Search...',
    analyzing: 'Analyzing...',
    noResults: 'No results',
    noResultsDetail: 'Try another query',
    cart: 'Cart',
    checkout: 'Checkout',
    orderHistory: 'ORDER HISTORY',
    minOrder: 'Min. Order',
    factoryMinOrder: 'Factory MOQ',
    inStock: 'In Stock',
    preorder: 'Pre-order',
    addToCart: 'Add to Cart',
    edit: 'Edit',
    add: 'Add',
    openClientChat: 'Contact Manager',
    balance: 'BALANCE',
    status: 'STATUS',
    debt: 'Debt',
    notPaid: 'Not Paid',
    overpayment: 'Overpayment',
    payments: 'PAYMENTS',
    uploadCheck: 'Upload Receipt',
    recordPayment: 'Record Payment',
    amountPaid: 'PAID',
    remaining: 'REMAINING',
    cash: 'Cash',
    transfer: 'Transfer',
    card: 'Card',
    reorder: 'REORDER',
    factoryOrders: 'ORDERED FROM FACTORY',
    stockOrder: 'FROM STOCK',
    sku: 'SKU',
    gsm: 'Weight (GSM)',
    width: 'Width (cm)',
    youtubeLink: 'YouTube ID (11 chars)',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    reset: 'Reset',
    analyzingText: 'Searching matches...',
    catalog: 'Catalog',
    profile: 'Profile',
    orders: 'Orders',
    stock: 'Stock',
    stats: 'Statistics',
    settings: 'Settings',
    adminView: 'Admin View',
    clientView: 'Client View',
    switchRole: 'Switch Role',
    title: 'Title',
    description: 'Description',
    category: 'Category',
    type: 'Type',
    price: 'Price',
    priceUsd: 'Price USD',
    historyEmpty: 'History is empty',
    cartEmpty: 'Cart is empty',
    stockWarning: 'Note: Split Order',
    stockPart: 'From Stock',
    factoryPart: 'From Factory',
    totalEst: 'Total',
    uploadLogo: 'Upload Logo',
    managerContact: 'Contact Manager',
    revenue: 'Revenue',
    systemDebt: 'System Debt',
    reports: 'Reports',
    reportsCenter: 'Reports Center',
    selectReports: 'Select reports to download',
    downloadSelected: 'Download Selected',
    clientLedger: 'Client Ledger',
    client: 'Client',
    date: 'Date',
    amount: 'Amount',
    totalItems: 'Total Items',
    avgCheck: 'Avg Check',
    expenses: 'Expenses',
    profit: 'Profit',
    netProfit: 'Net Profit',
    purchasePrice: 'Purchase Price',
    logistics: 'Logistics',
    supplier: 'Supplier',
    supplierWechat: 'Supplier WeChat',
    factoryDiscount: 'Factory Discount (-3%)',
    yourSavings: 'You save',
    addExpense: 'Add Expense',
    receipt: 'Receipt',
    expenseDetails: 'Expense Details',
    availableQty: 'Available Qty',
    searchHistory: 'Search History',
    visualSearchGallery: 'Visual Search Gallery',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    colorCard: 'Color Card',
    selectColor: 'Select Color',
    variant: 'Variant',
    addVariant: 'Add Variant',
    factoryMoqError: 'Below Factory Minimum',
    factoryMoqDetail: 'Remaining order is less than factory minimum run.',
    increaseOrder: 'Increase Order',
    favorites: 'Favorites',
    saved: 'Saved',
    checkCustomer: 'Customer Verification',
    allClients: 'All Clients',
    selectClient: 'Select Client',
    paymentHistory: 'Payment History',
    viewReceipt: 'View Receipt',
    userManagement: 'User Management',
    deleteUser: 'Delete',
    role: 'Role',

    // Reports Names
    rep_supplier: 'Supplier Report',
    rep_clients: 'Clients List',
    rep_client_ledger: 'Client Ledger (Financial)',
    rep_sales_all: 'Sales Report (All)',
    rep_sales_fabric: 'Sales Report (Fabrics)',
    rep_sales_hardware: 'Sales Report (Hardware)',
    rep_expenses: 'Expenses Report',
    rep_income: 'Income Report',
    rep_inventory: 'Inventory (Stock)',
    rep_search_logs: 'Search Logs',

    statuses: {
      ORDERED: 'ORDERED',
      CONFIRMED: 'CONFIRMED',
      PRODUCTION: 'PRODUCTION',
      TRANSIT: 'IN TRANSIT',
      WAREHOUSE: 'IN WAREHOUSE',
      READY_FOR_DELIVERY: 'READY',
      DELIVERED: 'DELIVERED',
      CANCELLED: 'CANCELLED'
    },
    expenseCategories: {
      RENT: 'Rent',
      UTILITIES: 'Utilities',
      SALARY: 'Salary',
      LOGISTICS: 'Logistics',
      MARKETING: 'Marketing',
      OTHER: 'Other'
    }
  },
  ky: {
    brandName: 'Jolu Textile',
    slogan: 'Биз кездемени түзөбүз — сиз моданы жаратасыз',
    selectCategory: 'Категория тандаңыз',
    fabrics: 'Кездемелер',
    hardware: 'Аксессуары',
    searchPlaceholder: 'Издөө...',
    analyzing: 'Талданууда...',
    noResults: 'Эч нерсе табылган жок',
    noResultsDetail: 'Башкача жазып көрүңүз',
    cart: 'Себет',
    checkout: 'Заказ берүү',
    orderHistory: 'ЗАКАЗДАРДЫН ТАРЫХЫ',
    minOrder: 'Мин. заказ',
    factoryMinOrder: 'Фабрика мин. заказ',
    inStock: 'Кампада бар',
    preorder: 'Алдын ала заказ',
    addToCart: 'Себетке кошуу',
    edit: 'Өзгөртүү',
    add: 'Кошуу',
    openClientChat: 'Менеджер менен байланыш',
    balance: 'БАЛАНС',
    status: 'АБАЛЫ',
    debt: 'Карыз',
    notPaid: 'Төлөнгөн эмес',
    overpayment: 'Ашыкча төлөм',
    payments: 'ТӨЛӨМДӨР',
    uploadCheck: 'Чек жүктөө',
    recordPayment: 'Төлөмдү жазуу',
    amountPaid: 'ТӨЛӨНДҮ',
    remaining: 'КАЛДЫК',
    cash: 'Накталай',
    transfer: 'Которуу',
    card: 'Карта',
    reorder: 'КАЙРА ЗАКАЗ',
    factoryOrders: 'ФАБРИКАГА ЗАКАЗ',
    stockOrder: 'КАМПАДАН',
    sku: 'Артикул',
    gsm: 'Тыгыздыгы (GSM)',
    width: 'Туурасы (см)',
    youtubeLink: 'YouTube ID (11 белги)',
    confirm: 'Ырастоо',
    cancel: 'Жокко чыгаруу',
    save: 'Сактоо',
    close: 'Жабуу',
    reset: 'Тазалоо',
    analyzingText: 'Окшоштуктарды издөө...',
    catalog: 'Каталог',
    profile: 'Профиль',
    orders: 'Заказдар',
    stock: 'Кампа',
    stats: 'Статистика',
    settings: 'Жөндөөлөр',
    adminView: 'Админ-көрүнүш',
    clientView: 'Клиент-көрүнүш',
    switchRole: 'Ролду алмаштыруу',
    title: 'Аты',
    description: 'Сүрөттөмө',
    category: 'Категория',
    type: 'Түрү',
    price: 'Баасы',
    priceUsd: 'Баасы USD',
    historyEmpty: 'Тарых бош',
    cartEmpty: 'Себет бош',
    stockWarning: 'Эскертүү: Заказ бөлүндү',
    stockPart: 'Кампадан',
    factoryPart: 'Фабрикадан',
    totalEst: 'Жалпы',
    uploadLogo: 'Логотип жүктөө',
    managerContact: 'Менеджер менен байланыш',
    revenue: 'Киреше',
    systemDebt: 'Жалпы карыз',
    reports: 'Отчёттор',
    reportsCenter: 'Отчёттор Борбору',
    selectReports: 'Жүктөп алуу үчүн отчётторду тандаңыз',
    downloadSelected: 'Тандалгандарды жүктөө',
    clientLedger: 'Клиенттер китеби',
    client: 'Клиент',
    date: 'Күнү',
    amount: 'Сумма',
    totalItems: 'Жалпы товарлар',
    avgCheck: 'Орточо чек',
    expenses: 'Чыгымдар',
    profit: 'Пайда',
    netProfit: 'Таза пайда',
    purchasePrice: 'Сатып алуу баасы',
    logistics: 'Логистика',
    supplier: 'Поставщик',
    supplierWechat: 'Поставщик WeChat',
    factoryDiscount: 'Фабрика арзандатуусу (-3%)',
    yourSavings: 'Сиз үнөмдөдүңүз',
    addExpense: 'Чыгым кошуу',
    receipt: 'Чек',
    expenseDetails: 'Чыгым чоо-жайы',
    availableQty: 'Кампада бар',
    searchHistory: 'Издөө тарыхы',
    visualSearchGallery: 'Визуалдык издөө галереясы',
    selectAll: 'Баарын тандоо',
    deselectAll: 'Баарын алуу',
    colorCard: 'Түстөр картасы',
    selectColor: 'Түс тандаңыз',
    variant: 'Вариант',
    addVariant: 'Вариант кошуу',
    factoryMoqError: 'Фабриканын минимуму жетпейт',
    factoryMoqDetail: 'Калган бөлүгү фабриканын минимумунан аз.',
    increaseOrder: 'Заказды көбөйтүңүз',
    favorites: 'Тандалгандар',
    saved: 'Сакталды',
    checkCustomer: 'Кардарды текшерүү',
    allClients: 'Бардык кардарлар',
    selectClient: 'Кардарды тандаңыз',
    paymentHistory: 'Төлөм тарыхы',
    viewReceipt: 'Чекти көрүү',
    userManagement: 'Колдонуучуларды башкаруу',
    deleteUser: 'Өчүрүү',
    role: 'Ролу',
    
    // Reports Names
    rep_supplier: 'Поставщиктер боюнча отчёт',
    rep_clients: 'Клиенттердин тизмеси',
    rep_client_ledger: 'Финансылык китепче (Ledger)',
    rep_sales_all: 'Сатуу отчёту (Жалпы)',
    rep_sales_fabric: 'Сатуу (Кездеме)',
    rep_sales_hardware: 'Сатуу (Фурнитура)',
    rep_expenses: 'Чыгымдар отчёту',
    rep_income: 'Киреше отчёту',
    rep_inventory: 'Инвентаризация (Калдыктар)',
    rep_search_logs: 'Издөө тарыхы',

    statuses: {
      ORDERED: 'ЗАКАЗ БЕРИЛДИ',
      CONFIRMED: 'ЫРАСТАЛДЫ',
      PRODUCTION: 'ӨНДҮРҮШТӨ',
      TRANSIT: 'ЖОЛДО',
      WAREHOUSE: 'КАМПАДА',
      READY_FOR_DELIVERY: 'ДАЯР',
      DELIVERED: 'ЖЕТКИРИЛДИ',
      CANCELLED: 'ЖОККО ЧЫГАРЫЛДЫ'
    },
    expenseCategories: {
      RENT: 'Аренда',
      UTILITIES: 'Коммунальные',
      SALARY: 'Зарплата',
      LOGISTICS: 'Логистика',
      MARKETING: 'Маркетинг',
      OTHER: 'Башка'
    }
  }
};

export const STATUS_COLORS: Record<OrderStatus, string> = {
  [OrderStatus.ORDERED]: 'bg-blue-600',
  [OrderStatus.CONFIRMED]: 'bg-cyan-500',
  [OrderStatus.PRODUCTION]: 'bg-orange-500',
  [OrderStatus.TRANSIT]: 'bg-purple-500',
  [OrderStatus.WAREHOUSE]: 'bg-teal-600',
  [OrderStatus.READY_FOR_DELIVERY]: 'bg-green-500',
  [OrderStatus.DELIVERED]: 'bg-emerald-700',
  [OrderStatus.CANCELLED]: 'bg-red-600'
};

export const FABRIC_CATEGORIES = [
  'Cotton', 'Linen', 'Silk', 'Wool', 'Polyester', 'Denim', 'Knit', 'Lace', 'Leather', 'Velvet', 'Chiffon', 'Canvas', 'Viscose'
];

export const HARDWARE_CATEGORIES = [
  'Zippers', 'Buttons', 'Rivets', 'Buckles', 'Thread', 'Interlining', 'Labels', 'Elastic', 'Velcro', 'Eyelets', 'Snaps', 'Hooks'
];

export const EXPENSE_CATEGORIES = Object.values(ExpenseCategory);

export const MOCK_PRODUCTS: Product[] = []; // Removed for brevity, functionality remains in DB
export const MOCK_USER: User = {
  id: 'u-1',
  telegram_id: '12345678',
  username: 'johndoe',
  name: 'John Doe',
  brand: 'PREMIUM WEAR LTD',
  phone: '+996 555 123 456',
  role: Role.USER,
  balance: 0 
};

export const MOCK_SETTINGS: AppSettings = {
  defaultLanguage: 'ru',
  contact: {
    destinationValue: 'shilu_manager',
    messageTemplate: 'Hello! I want to confirm order {orderId} for brand {brand}. Total: ${total}',
    managerName: 'Manager Name',
    managerTG: 'shilu_manager'
  },
  globalMargin: 0
};

export const MOCK_ORDERS: Order[] = [];
